version: '3'
services:
  pages:
    image: pages
    build:
      context: .
      dockerfile: Dockerfile.pages
    container_name: pages
    working_dir: /app
    command: ["sh", "-c", "/utils/wait_for_it.sh pages-pg:5432 ; diesel migration run ; cargo run"]
    volumes:
      - ..:/app
      - stq_cargo_cache:/usr/local/cargo
    environment:
      - DATABASE_URL=postgresql://pages:pages@pages-pg/pages
      - "RUST_LOG=pages=debug"
    expose:
      - 8000
    stdin_open: true
    depends_on:
      - pages-pg

  pages-pg:
    image: postgres:10
    container_name: pages-pg
    volumes:
      - stq-pages-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pages
      - POSTGRES_DB=pages
      - POSTGRES_PASSWORD=pages
    ports:
      - "5433:5432"

volumes:
  stq_cargo_cache:
  stq-pages-postgres-data:

networks:
  default:
    external:
      name: storiqa
